metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: prometheus
  period: 10s
  hosts: ["prometheus:9090"]
  metrics_path: '/federate'
  query:
    'match[]': '{__name__!=""}'
  use_types: true
  rate_counters: false
  enabled: true

#- module: prometheus
#  metricsets: ["remote_write"]
#  host: "metricbeat"
#  port: "9201"

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.dashboards.enabled: true
setup.kibana.host: "http://kibana:5601"
